git clone https://gitlab.com/videowiki/client
git clone https://gitlab.com/videowiki/api-gateway-service
git clone https://gitlab.com/videowiki/websockets-service
git clone https://gitlab.com/videowiki/apikey-api-service
git clone https://gitlab.com/videowiki/article-api-service
git clone https://gitlab.com/videowiki/auth-service
git clone https://gitlab.com/videowiki/comment-api-service
git clone https://gitlab.com/videowiki/email-service
git clone https://gitlab.com/videowiki/invitation-response-api-service
git clone https://gitlab.com/videowiki/noise-cancellation-video-api-service
git clone https://gitlab.com/videowiki/notification-api-service
git clone https://gitlab.com/videowiki/organization-api-service
git clone https://gitlab.com/videowiki/socket-connection-service
git clone https://gitlab.com/videowiki/storage-service
git clone https://gitlab.com/videowiki/subtitles-api-service
git clone https://gitlab.com/videowiki/text-to-speech-service
git clone https://gitlab.com/videowiki/translation-api-service
git clone https://gitlab.com/videowiki/translation-export-api-service
git clone https://gitlab.com/videowiki/user-api-service
git clone https://gitlab.com/videowiki/video-api-service
git clone https://gitlab.com/videowiki/video-tutorial-contribution-api-service
git clone https://gitlab.com/videowiki/audio-processor-service
git clone https://gitlab.com/videowiki/translator-service
git clone https://gitlab.com/videowiki/noise-cancellation-api-service
git clone https://gitlab.com/videowiki/exporter-service
git clone https://gitlab.com/videowiki/bg-music-extractor-service
git clone https://gitlab.com/videowiki/transcriber-service
git clone https://gitlab.com/videowiki/video-noise-cancellation-service
