
version: '3'
# DEV DOCKER COMPOSE
services:
### DEPENDENCIES ###
    redis-server:
        image: redis
        restart: always
########################################################################################
    mongo-server:
        image: mongo:4.0.10
        restart: always
        volumes:
        - ./data:/data/db
        - ./data:/var/lib/mongodb 
########################################################################################
    rabbitmq-server:
        image: rabbitmq
        restart: always
########################################################################################
    nginx_server:
        image: nginx:1.14.0
        restart: always 
        ports:
            - 80:80
            - 443:443
        volumes:
        - ./nginx_config:/etc/nginx/conf.d

########################################################################################
    client:
        restart: on-failure
        image: registry.gitlab.com/videowiki/client:4
        env_file:
            - docker-compose.env
########################################################################################
    api-service:
        restart: on-failure
        image: registry.gitlab.com/videowiki/api-service:4
        env_file:
            - docker-compose.env
        depends_on:
            - redis-server
            - mongo-server
            - rabbitmq-server
    audio-processor-service:
        restart: on-failure
        image: registry.gitlab.com/videowiki/audio-processor-service:4
        env_file:
            - docker-compose.env
        depends_on:
            - api-gateway-service

    translator-service:
        restart: on-failure
        image: registry.gitlab.com/videowiki/translator-service:4
        env_file:
            - docker-compose.env
        depends_on:
            - api-gateway-service

    exporter-service:
        restart: on-failure
        image: registry.gitlab.com/videowiki/exporter-service:4
        env_file:
            - docker-compose.env
        depends_on:
            - api-gateway-service

    bg-music-extractor-service:
        restart: on-failure
        image: registry.gitlab.com/videowiki/bg-music-extractor-service:4
        env_file:
            - docker-compose.env
        depends_on:
            - api-gateway-service
    automatic-video-break-service:
        restart: on-failure
        image: registry.gitlab.com/videowiki/automatic-video-break-service:4
        env_file:
            - docker-compose.env
        depends_on:
            - api-gateway-service
    transcriber-service:
        restart: on-failure
        image: registry.gitlab.com/videowiki/transcriber-service:4
        env_file:
            - docker-compose.env
        depends_on:
            - api-gateway-service

    transcriber-cronjob-service:
        restart: on-failure
        image: registry.gitlab.com/videowiki/transcriber-cronjob-service:4
        env_file:
            - docker-compose.env
        depends_on:
            - api-gateway-service


