
version: '3'
# DEV DOCKER COMPOSE
services:
### DEPENDENCIES ###
    redis-server:
        image: redis
########################################################################################
    mongo-server:
        image: mongo:4.0.10
        restart: on-failure
        # environment:
        #   - MONGO_INITDB_ROOT_USERNAME=root
        #   - MONGO_INITDB_ROOT_PASSWORD=root
        #   - MONGO_INITDB_DATABASE=tailored_videowiki
        volumes:
        - ./data:/data/db
        - ./data:/var/lib/mongodb 
########################################################################################
    rabbitmq-server:
        image: rabbitmq
        restart: on-failure
########################################################################################
    nginx_server:
        image: nginx:1.14.0
        restart: on-failure
        ports:
            - 80:80
        volumes:
        - ./nginx_config:/etc/nginx/conf.d

########################################################################################
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - ./client:/client
        ports:
            - 3000:3000
########################################################################################
    api-gateway-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./api-gateway-service
            dockerfile: Dockerfile.dev

        depends_on:
            - redis-server
            - mongo-server
            - rabbitmq-server
        volumes:
            - ./api-gateway-service:/api-gateway-service
        ports:
            - 4000:4000
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']
    websockets-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./websockets-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./websockets-service:/websockets-service
        ports:
            - 4010:4000
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']


    apikey-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./apikey-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./apikey-api-service:/apikey-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    article-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./article-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./article-api-service:/article-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    auth-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./auth-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./auth-service:/auth-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    comment-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./comment-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./comment-api-service:/comment-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    email-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./email-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./email-service:/email-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    invitation-response-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./invitation-response-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./invitation-response-api-service:/invitation-response-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    noise-cancellation-video-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./noise-cancellation-video-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./noise-cancellation-video-api-service:/noise-cancellation-video-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    notification-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./notification-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./notification-api-service:/notification-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    organization-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./organization-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./organization-api-service:/organization-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    socket-connection-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./socket-connection-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./socket-connection-service:/socket-connection-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    storage-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./storage-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./storage-service:/storage-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    subtitles-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./subtitles-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./subtitles-api-service:/subtitles-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    text-to-speech-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./text-to-speech-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./text-to-speech-service:/text-to-speech-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    translation-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./translation-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./translation-api-service:/translation-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    translation-export-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./translation-export-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./translation-export-api-service:/translation-export-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    user-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./user-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./user-api-service:/user-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    video-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./video-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./video-api-service:/video-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    video-tutorial-contribution-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./video-tutorial-contribution-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./video-tutorial-contribution-api-service:/video-tutorial-contribution-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    audio-processor-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./audio-processor-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./audio-processor-service:/audio-processor-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    translator-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./translator-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./translator-service:/translator-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    noise-cancellation-api-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./noise-cancellation-api-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./noise-cancellation-api-service:/noise-cancellation-api-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    exporter-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./exporter-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./exporter-service:/exporter-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    bg-music-extractor-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./bg-music-extractor-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./bg-music-extractor-service:/bg-music-extractor-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    transcriber-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./transcriber-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./transcriber-service:/transcriber-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    video-noise-cancellation-service:
        restart: on-failure
        env_file:
            - docker-compose.env
        build:
            context: ./video-noise-cancellation-service
            dockerfile: Dockerfile.dev
        volumes:
            - ./video-noise-cancellation-service:/video-noise-cancellation-service
        command: ['./wait-for-it.sh', 'rabbitmq-server:5672', '-s', '-t', '60', '--', 'npm', 'run', 'docker:prod']

    
