version: '3'
# DEV DOCKER COMPOSE
services:
  redis_server:
    image: redis
########################################################################################
  mongo_server:
    image: mongo:4.0.10
    restart: always
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root
    #   - MONGO_INITDB_DATABASE=tailored_videowiki
    volumes:
    - ./data:/data/db
    - ./data:/var/lib/mongodb 
########################################################################################
  rabbitmq_server:
    image: rabbitmq
    restart: always
########################################################################################
  nginx_server:
      image: nginx:1.14.0
      restart: always
      ports:
          - 80:80
      volumes:
        - ./nginx_config:/etc/nginx/conf.d
########################################################################################
  tvw_frontend:
    build:
      context: ./tvw_frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./tvw_frontend:/tvw_frontend
      - /tvw_frontend/node_modules
    ports:
      - 3000:3000
  tvw_backend:
    env_file:
      - docker-compose.env
    build:
      context: ./tvw_backend
      dockerfile: Dockerfile.dev

    restart: always
    depends_on:
      - redis_server
      - mongo_server
      - rabbitmq_server
    volumes:
      - ./tvw_backend:/tvw_backend
    ports:
      - 4000:4000
    command: ['./wait-for-it.sh', 'rabbitmq_server:5672', '-s', '-t', '20', '--', 'npm', 'run', 'dev']
########################################################################################
  tvw_audio_processor:
    env_file:
      - docker-compose.env
    build:
      context: ./tvw_audio_processor
      dockerfile: Dockerfile.dev
    volumes:
    - ./tvw_audio_processor:/tvw_audio_processor
    # ports:
    #   - 4001:4001
    # command: ['npm', 'run', 'dev']
    depends_on:
      - tvw_backend
    command: ['./wait-for-it.sh', 'tvw_backend:4000', '-s', '-t', '15', '--', 'npm', 'run', 'dev']
########################################################################################
  tvw_exporter:
    env_file:
      - docker-compose.env
    build:
      context: ./tvw_exporter
      dockerfile: Dockerfile.dev
    volumes:
    - ./tvw_exporter:/tvw_exporter
    # command: ['npm', 'run', 'dev']
    depends_on:
      - tvw_backend
    command: ['./wait-for-it.sh', 'tvw_backend:4000', '-s', '-t', '15', '--', 'npm', 'run', 'dev']
########################################################################################
    
  tvw_transcriber:
    env_file:
      - docker-compose.env
    build:
      context: ./tvw_transcriber
      dockerfile: Dockerfile.dev
    volumes:
    - ./tvw_transcriber:/tvw_transcriber
    # command: ['npm', 'run', 'dev']
    depends_on:
      - tvw_backend
    command: ['./wait-for-it.sh', 'tvw_backend:4000', '-s', '-t', '15', '--', 'npm', 'run', 'dev']
########################################################################################
    
  tvw_translator:
    env_file:
      - docker-compose.env
    build:
      context: ./tvw_translator
      dockerfile: Dockerfile.dev
    volumes:
    - ./tvw_translator:/tvw_translator
    # command: ['npm', 'run', 'dev']
    depends_on:
      - tvw_backend
    command: ['./wait-for-it.sh', 'tvw_backend:4000', '-s', '-t', '15', '--', 'npm', 'run', 'dev']

########################################################################################
  tvw_spleeter:
    env_file:
      - docker-compose.env
    build:
      context: ./tvw_spleeter
      dockerfile: Dockerfile.dev
    volumes:
    - ./tvw_spleeter:/tvw_spleeter
    # command: ['npm', 'run', 'dev']
    depends_on:
      - tvw_backend
    command: ['./wait-for-it.sh', 'tvw_backend:4000', '-s', '-t', '15', '--', 'npm', 'run', 'dev']