
apiVersion: skaffold/v1beta2
kind: Config

build:
    local:
      push: false
    artifacts:

      - image: client
        context: client # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: api-gateway-service
        context: api-gateway-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: apikey-api-service
        context: apikey-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: article-api-service
        context: article-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: auth-service
        context: auth-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: comment-api-service
        context: comment-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: email-service
        context: email-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: invitation-response-api-service
        context: invitation-response-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: noise-cancellation-video-api-service
        context: noise-cancellation-video-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: notification-api-service
        context: notification-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: organization-api-service
        context: organization-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: socket-connection-service
        context: socket-connection-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: storage-service
        context: storage-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: subtitles-api-service
        context: subtitles-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: text-to-speech-service
        context: text-to-speech-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: translation-api-service
        context: translation-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: translation-export-api-service
        context: translation-export-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: user-api-service
        context: user-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: video-api-service
        context: video-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: video-tutorial-contribution-api-service
        context: video-tutorial-contribution-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: websockets-service
        context: websockets-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: audio-processor-service
        context: audio-processor-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: translator-service
        context: translator-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: noise-cancellation-api-service
        context: noise-cancellation-api-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: exporter-service
        context: exporter-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: bg-music-extractor-service
        context: bg-music-extractor-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: transcriber-service
        context: transcriber-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
      - image: video-noise-cancellation-service
        context: video-noise-cancellation-service # FOLDER THAT HAVE Dockerfile
        docker:
          dockerfile: Dockerfile.dev
        sync:
          '**/*.js': .
          '**/*.css': .
          '**/*.scss': .
          '**/*.html': .
deploy:
    kubectl:
      manifests:

        - /home/hassan/tvw/videowiki/dev/client-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/api-gateway-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/apikey-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/article-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/auth-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/comment-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/email-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/invitation-response-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/noise-cancellation-video-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/notification-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/organization-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/socket-connection-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/storage-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/subtitles-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/text-to-speech-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/translation-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/translation-export-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/user-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/video-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/video-tutorial-contribution-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/websockets-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/audio-processor-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/translator-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/noise-cancellation-api-service-api-deployment.yml
        - /home/hassan/tvw/videowiki/dev/exporter-service-worker-deployment.yml
        - /home/hassan/tvw/videowiki/dev/bg-music-extractor-service-worker-deployment.yml
        - /home/hassan/tvw/videowiki/dev/transcriber-service-worker-deployment.yml
        - /home/hassan/tvw/videowiki/dev/video-noise-cancellation-service-worker-deployment.yml
