
apiVersion: apps/v1
kind: Deployment
metadata:
    name: exporter-service-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: exporter-service
    template:
        metadata:
            labels:
                component: exporter-service
                stage: dev
        spec:
            containers:
            - name: exporter-service
              imagePullPolicy: Always
              image: exporter-service
              envFrom:
               - secretRef:
                    name: videowikisecretkeys


