
apiVersion: apps/v1
kind: Deployment
metadata:
    name: video-noise-cancellation-service-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: video-noise-cancellation-service
    template:
        metadata:
            labels:
                component: video-noise-cancellation-service
                stage: dev
        spec:
            containers:
            - name: video-noise-cancellation-service
              imagePullPolicy: Always
              image: video-noise-cancellation-service
              envFrom:
               - secretRef:
                    name: videowikisecretkeys


